---
title: "git_00"
author: "Dom Ciriello"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Blow, blow your trumpets till they crack,  
Ye little men of little souls!  
And bid them huddle at your back -  
Gold-sucking leeches, shoals on shoals!  
Fill all the air with hungry wails -  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

He is that fallen lance that lies as hurled,  
That lies unlifted now, come dew, come rust,  
But still lies pointed as it plowed the dust.  
If we who sight along it round the world,  
See nothing worthy to have been its mark,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

'He is my friend,' I said,--  
'Be patient!' Overhead  
The skies were drear and dim;  
And lo! the thought of him  
Smited on my heart--and then  
The sun shone out again!  
  
'He is my friend!' The words  
Brought summer and the birds;  
And all my winter-time  
Thawed into running rhyme  
And rippled into song,  
Warm, tender, brave, and strong.  
  
And so it sings to-day.--  
So may it sing alway!  
Though waving grasses grow  
Between, and lilies blow  
Their trills of perfume clear  
As laughter to the ear,  
Let each mute measure end  
With 'Still he is thy friend.'  
  